name: auto merge on PR approval

on:
  pull_request:
    types: [labeled] # other action types => opened, unlabeled
  pull_request_review:
    types: [submitted] # other action types => edited, dismissed
  pull_request_review_comment:
    types: [created] # other action types => edited, deleted

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Auto merge on PR if review state is approved or PR is labelled approved or PR comment contains /fast-forward
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      if: env.ACCESS_TOKEN != null && env.USER_EMAIL != null && env.USER_NAME != null && (github.event.review.state == 'approved' || github.event.label.name == 'approved' || contains(github.event.review.body, '/fast-forward'))
      run : |
        echo "[LOG] Clone source repo"
        git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git temp && cd temp

        echo "[LOG] Setup global config"
        git config --global user.email "${{ secrets.USER_EMAIL }}"
        git config --global user.name "${{ secrets.USER_NAME }}"

        echo "[LOG] Switch to head_ref branch"
        git switch ${{ github.event.pull_request.head.ref }}

        echo "[LOG] Switch to base_ref branch"
        git switch ${{ github.event.pull_request.base.ref }}

        echo "[LOG] Locally Merge head_ref branch to base_ref branch with --no-commit --ff-only flag"
        git merge ${{ github.event.pull_request.head.ref }} --no-commit --ff-only

        echo "[LOG] Update remote origin repo"
        git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git

        echo "[LOG] Force push base_ref branch to origin"
        git push origin ${{ github.event.pull_request.base.ref }} -f

        echo "[LOG] Remove folder / Clean up"
        cd .. && rm -rf temp
