name: auto merge on PR approval

on:
  pull_request:
    types: [labeled] # other action types => opened, unlabeled
  pull_request_review:
    types: [submitted] # other action types => edited, dismissed

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Auto merge on PR if review state is approved or PR is labelled approved
      env:
        SYNC_ACCESS_TOKEN: ${{ secrets.SYNC_ACCESS_TOKEN }}
      if: env.SYNC_ACCESS_TOKEN != null && (github.event.review.state == 'approved' || github.event.label.name == 'approved')
      run : |
        echo "[LOG] Clone source repo"
        git clone https://github.com/$GITHUB_REPOSITORY.git temp
        cd temp

        echo "[LOG] Setup global config"
        git config --global user.email "${{ secrets.SYNC_USER_EMAIL }}"
        git config --global user.name "${{ secrets.SYNC_USER_NAME }}"

        echo "[LOG] Write access token to token.txt file"
        echo ${{ secrets.SYNC_ACCESS_TOKEN }} > token.txt

        echo "[LOG] Login with GitHub Cli && Merge PR using GitHub Cli"
        gh auth login --with-token < token.txt && gh pr merge ${{ github.event.pull_request.number }} -m

        echo "[LOG] Remove folder / Clean up"
        cd ..
        rm -rf temp