name: sync repo with source repo

on:
  # schedule:
  #   - cron:  '*/10 * * * *' # every 10 minutes
  workflow_dispatch:
    inputs:
      SYNC_SKIP_PATTERN:
        description: Sync Skip Pattern
        default: main # will skip branches containing the work "main"
        required: true
      DEFAULT_BRANCH:
        description: Default Branch
        default: main
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: pull source repo into this repo
      env:
        SYNC_ACCESS_TOKEN: ${{ secrets.SYNC_ACCESS_TOKEN }}
        SYNC_SOURCE_REPO: ${{ secrets.SYNC_SOURCE_REPO }}
      if: env.SYNC_ACCESS_TOKEN != null && env.SYNC_SOURCE_REPO != null
      run : |
        echo "[LOG] Clone this repo"
        git clone https://x-access-token:${{ secrets.SYNC_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git temp && cd temp

        echo "[LOG] Add source repo as remote upstream repo"
        git remote add upstream https://x-access-token:${{ secrets.SYNC_ACCESS_TOKEN }}@github.com/${{ secrets.SYNC_SOURCE_REPO }}.git

        echo "[LOG] fetch all branches and detach head"
        git fetch --all && git checkout --detach -q

        echo "[LOG] Delete all branches not matching SYNC_SKIP_PATTERN on local repo"
        git branch | grep -v "* (HEAD detached at" | grep -v ${{ github.event.inputs.SYNC_SKIP_PATTERN }} | xargs -I branchname git branch -D branchname

        echo "[LOG] Checkout all branches on remote origin not matching SYNC_SKIP_PATTERN"
        for branch in $(git branch --all | grep '^\s*remotes/origin' | grep -v remotes/origin/HEAD | grep -v ${{ github.event.inputs.SYNC_SKIP_PATTERN }}); do
          git branch --track "${branch##*/}" "$branch"
        done

        echo "[LOG] Delete all branches not matching SYNC_SKIP_PATTERN & DEFAULT_BRANCH on remote origin repo"
        git branch | grep -v "* (HEAD detached at" | grep -v ${{ github.event.inputs.SYNC_SKIP_PATTERN }} | grep -v ${{ github.event.inputs.DEFAULT_BRANCH }} | xargs -I branchname git push origin --delete branchname

        echo "[LOG] Delete all branches not matching SYNC_SKIP_PATTERN on local repo"
        git branch | grep -v "* (HEAD detached at" | grep -v ${{ github.event.inputs.SYNC_SKIP_PATTERN }} | xargs -I branchname git branch -D branchname

        echo "[LOG] Checkout all branches on remote upstream not matching SYNC_SKIP_PATTERN"
        for branch in $(git branch --all | grep '^\s*remotes/upstream' | grep -v remotes/upstream/HEAD | grep -v ${{ github.event.inputs.SYNC_SKIP_PATTERN }}); do
          git branch --track "${branch##*/}" "$branch"
        done

        echo "[LOG] Force push all branches to origin"
        git push origin --all --force

        echo "[LOG] Remove folder / Clean up"
        cd .. && rm -rf temp
