name: sync repo with destination repo

on:
  push:
    branches:
      - '**' # matches every branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync source repo with destination repo
      env:
        SYNC_ACCESS_TOKEN: ${{ secrets.SYNC_ACCESS_TOKEN }}
        SYNC_DEST_REPO: ${{ secrets.SYNC_DEST_REPO }}
      if: env.SYNC_ACCESS_TOKEN != null && env.SYNC_DEST_REPO != null
      run : |
        echo "[LOG] Clone source repo"
        git clone https://github.com/$GITHUB_REPOSITORY.git temp
        cd temp

        echo "[LOG] Add destination repo as remote upstream repo"
        git remote add upstream https://x-access-token:${{ secrets.SYNC_ACCESS_TOKEN }}@github.com/${{ secrets.SYNC_DEST_REPO }}.git

        echo "[LOG] Delete origin HEAD refspec && Force push all branches to upstream repo"
        git remote set-head origin --delete && git push upstream refs/remotes/origin/*:refs/heads/* -f

        echo "[LOG] Remove folder / Clean up"
        cd ..
        rm -rf temp