name: sync repo with destination repo

on:
  push:
    branches:
      - '**' # matches every branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync source repo with destination repo
      env:
        SYNC_ACCESS_TOKEN: ${{ secrets.SYNC_ACCESS_TOKEN }}
      if: env.SYNC_ACCESS_TOKEN != null
      run : |
          echo "[LOG] Clone source repo"
          git clone https://github.com/$GITHUB_REPOSITORY.git temp
          cd temp

          echo "[LOG] Setup global config"
          git config --global user.email "${{ secrets.SYNC_USER_EMAIL }}"
          git config --global user.name "${{ secrets.SYNC_USER_NAME }}"

          echo "[LOG] Add destination repo as remote upstream repo"
          git remote add upstream https://x-access-token:${{ secrets.SYNC_ACCESS_TOKEN }}@github.com/${{ secrets.SYNC_DEST_REPO }}.git

          echo "[LOG] Force push all branches to upstream repo"
          # git push --all origin -f
          git push upstream refs/remotes/origin/*:refs/remotes/upstream* -f

          # echo "[LOG] Force push the branch that triggered the workflow to upstream repo"
          # git switch $GITHUB_REF_NAME
          # git push upstream $GITHUB_REF_NAME  -f

          echo "[LOG] Remove folder / Clean up"
          cd ..
          rm -rf temp