name: trigger say hello world workflow on dest repo

on:
  push:
    branches:
      - '**' # matches every branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: trigger say hello world workflow on dest repo
      env:
        SYNC_ACCESS_TOKEN: ${{ secrets.SYNC_ACCESS_TOKEN }}
      if: env.SYNC_ACCESS_TOKEN != null
      run : |
        echo "[LOG] trigger say hello world"
        curl --location --request POST 'https://api.github.com/repos/tunjioye/sync-dest-repo/actions/workflows/15564740/dispatches' \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Authorization: Bearer ${{ secrets.SYNC_ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "ref": "main",
              "inputs": {
                  "SYNC_SKIP_PATTERN": "hello now"
              }
          }'
